### ISSUE TITLE
OSHPark shows board bottom as white

### ISSUE THREAD

**Issue by leolobato** [chris-jh/mt32-pi-midi-hat#1]
I'm not experienced at all with producing/ordering PCBs but am looking forward to assembling this project.

I've tried uploading the Gerbers_v1_7.zip file to OSHPark and they showed an issue at the board bottom (see attached).

Is this something that is easily fixable?

![Screen Shot 2021-02-05 at 15 54 18](https://user-images.githubusercontent.com/134285/107049651-a6894200-67ca-11eb-95c9-1e42b6fe32dc.png)

**Comment by chris-jh** [comment]
the gerbers are made to JLCPCB Specification, so maybe this is the issue ?

I think you will need to use KiCad to make new Gerbers to OSHParks Specifications, or order from JLCPCB

**Comment by leolobato** [comment]
Thank you! I'll check JLCPCB.
