### ISSUE TITLE
Tracer is very close to mounting screw.

### ISSUE THREAD

**Issue by skadarnold** [chris-jh/mt32-pi-midi-hat#3]
Minor issue where the tracer next to this GPIO pin can be exposed when tightening mounting screws to raspberry pi case. Recommended using a washer or nylon screws when using version 1.7 of this hat. Causes the raspberry pi to short when turning on. Did not cause any damage from what I can tell as removing the screw allowed everything to work as it should. It is also worth mentioning that I tightened as normal, and did not necessarily over tighten this screw. 

![signal-2021-03-08-082729](https://user-images.githubusercontent.com/80274795/110350342-7a8af780-7fe8-11eb-86c5-602391b1884d.jpeg)

**Comment by chris-jh** [comment]
I will move it, when i get around, good call. Although i used nylon screws, so never noticed.

**Comment by chris-jh** [comment]
fixed
