### ISSUE TITLE
Link to MIDI connector is wrong

### ISSUE THREAD

**Issue by andresvettori** [chris-jh/mt32-pi-midi-hat#6]
The link https://www.mouser.co.uk/ProductDetail/490-SDS-50J  points to a 4 pin DIN receptacle, not 5 pin.

**Comment by chris-jh** [comment]
50 = 5 pin. look at the datasheet. not the image 🙂

**Comment by andresvettori** [comment]
Hi! thanks a lot for the Mt-32Pi Hat project, I'm preparing top build it myself (print the board) and I have a question. Does this board have any vias? If not, I'm thinking about soldering the header where I see there are tracks going into the header pins on both sides of the board....  and I don´t know how to do that. Thanks in advance!
